platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'Puckator' do
pod 'AHEasing', :git => 'https://github.com/warrenm/AHEasing.git'
pod 'MTMigration', '~> 0.0'
pod 'MagicalRecord', '~> 2.2'
pod 'FCFileManager', '~> 1.0'
pod 'HexColors', '~> 2.2.1'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'NSString-Hashes', '~> 1.2'
pod 'MBProgressHUD', '~> 0.8'
pod 'UIImageEffects', '~> 0.0'
pod 'RaptureXML', '~> 1.0'
pod 'AFNetworking', '~> 2.4'
pod 'zipzap', '~> 8.0'
pod 'ZipArchive', '~> 1.3'
pod 'SSZipArchive'
pod 'FXForms', '~> 1.2'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'FXKeychain', '~> 1.5'
pod 'CSStickyHeaderFlowLayout'
pod 'TLLayoutTransitioning', '~> 1.0'
pod 'TLIndexPathTools', '~> 0.3'
pod 'iOS-blur', '~> 0.0'
pod 'XHRealTimeBlur', '~> 1.4'
pod 'JWT', '~> 1.0'
pod 'DOSingleton', '~> 0.1'
pod 'AFSoundManager', '~> 1.2'
pod 'GraphKit', :git => 'https://github.com/lukedixon/GraphKit.git'
pod 'NSDate+Calendar', '~> 0.0'
pod 'FileMD5Hash', '~> 2.0'
pod 'UIImage-Resize', '~> 1.0'
pod 'WCFastCell', '~> 1.1'
pod 'CTCustomTableViewCell', '~> 2'
pod 'FXBlurView', '~> 1.6'
pod 'UIImage+animatedGif', '~> 0.1'
pod 'FMDB', '~> 2.5'
pod 'APProgressHUD', '~> 1.1'
pod 'TBXML', '~> 1.5'
pod 'UIColor+RandomColor', '~> 0.0'
pod 'MKFoundationKit', '~> 1.2.3'
pod 'MKMapViewZoom'
pod 'RMError', '~> 1.0'
pod 'NSThreadBlocks', '~> 0.0'
pod 'SoundManager', '~> 1.4'
pod 'OCMapView'
pod 'ObjectivePGP'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics', '~> 8.1.0'
pod 'AppCenter'

#pod 'UITableView-NXEmptyView', '~> 0.1'
end
